# Generated by Django 3.0.6 on 2020-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_doppler', '0003_populate_sardopplerextrametadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sardopplerextrametadata',
            name='polarization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
